name: C51 Build (SDCC)

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install SDCC Compiler
        run: sudo apt update && sudo apt install -y sdcc

      - name: Build C51 Project
        run: make  # 假设工程根目录有 Makefile，内容需适配 SDCC

      - name: Upload Compiled Artifact
        uses: actions/upload-artifact@v4  # 关键：v3 替换为 v4
        with:
          name: c51-output
          path: "*.hex"  # 匹配编译生成的 HEX 文件，可根据实际调整
